Cleanup Filtering
Mu2e/Production pull request #141
Opened 2021-11-24 18:58 UTC by brownd1978

Rationalize the DetStepFilters in primary production.  Add a generic bash script for generating primary fcl.  Cleanup the cosmic scripts.  Remove the cosmic 'loose' stream: this needs to become a dedicated S2 job for Offspill and Extracted.

2021-11-24 18:59 UTC, FNALbuild commented
Hi @brownd1978,
You have proposed changes to files in these packages:
- Scripts
- JobConfig

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 6772bfd87c4d79d02e87288283ed014f35cae117: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2021-11-24 19:41 UTC, FNALbuild commented
:umbrella: The tests failed for 6772bfd87c4d79d02e87288283ed014f35cae117.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 6772bfd87c4d79d02e87288283ed014f35cae117 at f56a31e8e19f3f91513d4f959c30dbe6b639215e |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/scons.log). Build time: 27 min 38 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/ceSteps.log)  |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/ceDigi.log) Return Code 24. |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/muDauSteps.log)  |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/ceMix.log) Return Code 24. |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 6772bfd87c4d79d02e87288283ed014f35cae117 after being merged into the base branch at f56a31e8e19f3f91513d4f959c30dbe6b639215e.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//107/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-11-27 02:30 UTC, soleti commented
@brownd1978 it looks like the validation failed, do you know the reason?

2021-11-27 13:41 UTC, kutschke commented
The job ceSteps is writing an output file named: dts.owner.CeEndpoint.version.sequencer.art

The jobs ceDigi and ceMix fail because they cannot find an input file named: dts.owner.ceSteps.dsconf.seq.art

If I look at previous CI jobs that worked, the output of ceSteps was named: dts.owner.ceSteps.dsconf.seq.art


From: Stefano Roberto Soleti ***@***.***>
Reply-To: Mu2e/Production ***@***.***>
Date: Friday, November 26, 2021 at 9:31 PM
To: Mu2e/Production ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Production] Cleanup Filtering (PR #141)


@brownd1978<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_brownd1978&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=9s0n95fodLptYW9rwpGMZbAgTLY7Ac7_ttu2fTvquJBbH1auzhKVi_3Vp7SyDWKq&s=sR-WjQBVoLjPO6n0RM1RdH8xcZXqmdaVWiUBWY6n4Pg&e=> it looks like the validation failed, do you know the reason?

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Production_pull_141-23issuecomment-2D980489004&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=9s0n95fodLptYW9rwpGMZbAgTLY7Ac7_ttu2fTvquJBbH1auzhKVi_3Vp7SyDWKq&s=976CXSm5IjdEmJLoz4d9FSFCVSTpoBlN236rRQliiiI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZWB4F3X6GU244WSXRLUOA7F7ANCNFSM5IWZGF5Q&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=9s0n95fodLptYW9rwpGMZbAgTLY7Ac7_ttu2fTvquJBbH1auzhKVi_3Vp7SyDWKq&s=ev_aEkQs0iBPEaqyjkeUOxJcnfMS1QdS-FGHtog-VaY&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=9s0n95fodLptYW9rwpGMZbAgTLY7Ac7_ttu2fTvquJBbH1auzhKVi_3Vp7SyDWKq&s=6HFKJJyhypsbPe-bB5Nj3kWOmR3fB015HQYzpSyAvXc&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=9s0n95fodLptYW9rwpGMZbAgTLY7Ac7_ttu2fTvquJBbH1auzhKVi_3Vp7SyDWKq&s=wfCqxXvB42EcxHRfMM2MxoGTmDbz_NXZaYtEMKTDxd0&e=>.

2021-11-28 01:13 UTC, brownd1978 commented
@FNALbuild run build test

2021-11-28 01:14 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for e5bab82c5e7bebf99e0a84d0c563cf4102358f2e: build  (Build queue has 1 jobs)

2021-11-28 01:57 UTC, FNALbuild commented
:sunny: The tests passed at e5bab82c5e7bebf99e0a84d0c563cf4102358f2e.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged e5bab82c5e7bebf99e0a84d0c563cf4102358f2e at f56a31e8e19f3f91513d4f959c30dbe6b639215e |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/scons.log). Build time: 27 min 40 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at e5bab82c5e7bebf99e0a84d0c563cf4102358f2e after being merged into the base branch at f56a31e8e19f3f91513d4f959c30dbe6b639215e.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//108/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-11-29 17:03 UTC, soleti approved these changes

2021-11-29 20:30 UTC, oksuzian requested changes

2021-11-29 20:30 UTC, oksuzian commented on JobConfig/cosmic/prolog.fcl
> -  signalFilter : {
I don't understand where this variable would be defined if we delete it

2021-11-29 20:30 UTC, oksuzian commented on JobConfig/cosmic/S1DSStops.fcl
> +  EndPath : [ genCountLogger, S1Output ]
Should it be S1Output->S1Path

2021-12-01 17:30 UTC, oksuzian approved these changes

2021-12-01 19:39 UTC, merged