Adding a PBI object for primary samples
Mu2e/Production pull request #80
Opened 2021-08-05 19:20 UTC by AndrewEdmonds11

In order to make things easier to analyze primary and mixed datasets with the same code (e.g. in TrkAna), I have added a PBI object to primary datasets. The new object always has a value of 1.

For mixing jobs (which generate their own PBI obect), I drop the primary PBI object on input.so that there is only one PBI object in the data stream.

I have tested the following:
 - CeEndpoint.fcl / OnSpill.fcl / Reco.fcl / TrkAnaReco.fcl produces trkana branches with `evtinfo.nprotons=1`
 - ceSteps.fcl / muDau.fcl / ceMix.fcl / Reco.fcl / TrkAnaReco.fcl produces trkana branches with `evtinfo.nprotons` corresponding to reaslitice proton bunch intensities
 
Everything seems to work as expected but I will see what the CI test show.

2021-08-05 19:20 UTC, FNALbuild commented
Hi @AndrewEdmonds11,
You have proposed changes to files in these packages:
- JobConfig

which require these tests: build.

@Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 508e2a13ba95191efb76d020e97d84637fcdef18: build  (Build queue has 1 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2021-08-05 19:49 UTC, FNALbuild commented
:sunny: The tests passed at 508e2a13ba95191efb76d020e97d84637fcdef18.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 508e2a13ba95191efb76d020e97d84637fcdef18 at c947ccaf2b0e4e6d66091c258cad8a58a49169d0 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/scons.log). Build time: 14 min 13 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 508e2a13ba95191efb76d020e97d84637fcdef18 after being merged into the base branch at c947ccaf2b0e4e6d66091c258cad8a58a49169d0.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//4/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-08-05 22:09 UTC, brownd1978 commented
Hi Andy,
Would it make more sense to create the fake PBI in the digitize job?   That would be more symmetric with mixing.

David Brown

> On Aug 5, 2021, at 12:49, Fermilab build bot account ***@***.***> wrote:
> 
> ﻿
> ☀️ The tests passed at 508e2a1.
> 
> Test	Result	Details
> merge	✅	Merged 508e2a1 at c947cca
> build (prof)	✅	Log file. Build time: 14 min 13 sec
> ceSimReco	✅	Log file.
> g4test_03MT	✅	Log file.
> transportOnly	✅	Log file.
> POT	✅	Log file.
> g4study	✅	Log file.
> cosmicSimReco	✅	Log file.
> cosmicOffSpill	✅	Log file.
> ceSteps	✅	Log file.
> ceDigi	✅	Log file.
> muDauSteps	✅	Log file.
> ceMix	✅	Log file.
> rootOverlaps	✅	Log file.
> g4surfaceCheck	✅	Log file.
> FIXME, TODO	✅	TODO (0) FIXME (0) in 0 files
> clang-tidy	✅	0 errors 0 warnings
> N.B. These results were obtained from a build of this Pull Request at 508e2a1 after being merged into the base branch at c947cca.
> 
> For more information, please check the job page here.
> Build artifacts are deleted after 5 days. If this is not desired, select Keep this build forever on the job page.
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-05 22:09 UTC, kutschke commented
This issue is required by  Mu2e/TrkAna#27

2021-08-05 22:09 UTC, kutschke commented
Andy, have you discussed this with Dave before he went on vacation?

2021-08-05 22:25 UTC, AndrewEdmonds11 commented
> 
> Hi Andy, Would it make more sense to create the fake PBI in the digitize job? That would be more symmetric with mixing. David Brown
>
Hi Dave. I could do it that way. I wasn't sure if anything in the digitize job is re-used in the mixing job so I thought it best to keep the new stuff confined to the primary job. If you don't see any issue with moving it to the digitize job, I can certaintly do that.

2021-08-05 22:25 UTC, AndrewEdmonds11 commented
>
> Andy, have you discussed this with Dave before he went on vacation?
>
Hi Rob. Yes, I discussed the idea with Dave last week but not a specific implementation. It looks like there might be another iteration before this is ready so it can wait until Dave gets back.

2021-08-05 22:29 UTC, kutschke commented
Thanks Andy.

From: Andrew Edmonds ***@***.***>
Reply-To: Mu2e/Production ***@***.***>
Date: Thursday, August 5, 2021 at 5:26 PM
To: Mu2e/Production ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Production] Adding a PBI object for primary samples (#80)


Andy, have you discussed this with Dave before he went on vacation?

Hi Rob. Yes, I discussed the idea with Dave last week but not a specific implementation. It looks like there might be another iteration before this is ready so it can wait until Dave gets back.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Production_pull_80-23issuecomment-2D893861103&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=uYUc0lcPdoAEqs6fLn88dpgwoNGF8ScyTuulhNT9nhY&s=ySkBR3RLwyMQOBkTyF0m6mrPvNhaccnVRUqPEa3XHfU&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZVUQAHMEHJYFXL7QZDT3MFXZANCNFSM5BUPFADQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=uYUc0lcPdoAEqs6fLn88dpgwoNGF8ScyTuulhNT9nhY&s=sCvqJHge15kGdiqVF_iwn6OugNLbJoC7DXtsDkfUqSQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=uYUc0lcPdoAEqs6fLn88dpgwoNGF8ScyTuulhNT9nhY&s=Vv2Xo74hz7QWskJI6JTsAbM6IEdo-ZZU_VBKAadwdao&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=uYUc0lcPdoAEqs6fLn88dpgwoNGF8ScyTuulhNT9nhY&s=YyrKMPcZ1NVN4OHGqBnccKqUZEZWJYv8dNUZqCRF9G0&e=>.

2021-08-09 23:30 UTC, brownd1978 requested changes

2021-08-09 23:30 UTC, brownd1978 commented on JobConfig/mixing/prolog.fcl
> +		  ]
This drop can be avoided if the PBI is created at digitization.

2021-08-09 23:30 UTC, brownd1978 commented on JobConfig/primary/prolog.fcl
> +    PBISim : {
I think this config should move to digitize/prolog, then  PBISim will get overwritten in mixing/prolog

2021-08-10 17:30 UTC, AndrewEdmonds11 commented
I've moved the primary PBISim from the primary job to the digitize job (a much cleaner solution). I've performed the same tests locally as before and everything seems OK. I will see what the CI tests bring up too

2021-08-10 17:31 UTC, AndrewEdmonds11 commented
@FNALbuild run build test

2021-08-10 17:32 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 78e2cde1cf0d1e61274a6335edc17c17e15d7904: build  (Build queue has 2 jobs)

2021-08-10 18:21 UTC, FNALbuild commented
:sunny: The tests passed at 78e2cde1cf0d1e61274a6335edc17c17e15d7904.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 78e2cde1cf0d1e61274a6335edc17c17e15d7904 at c947ccaf2b0e4e6d66091c258cad8a58a49169d0 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/scons.log). Build time: 27 min 25 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 78e2cde1cf0d1e61274a6335edc17c17e15d7904 after being merged into the base branch at c947ccaf2b0e4e6d66091c258cad8a58a49169d0.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-production-build-test//8/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-08-10 22:13 UTC, brownd1978 approved these changes
thanks Andy!

2021-08-10 22:13 UTC, merged